/**
 * OMC Office Management Course — COMPUTER BASIC (50 single-choice questions).
 * seedKey values are stable: TNS-CB-OMC-001 … TNS-CB-OMC-050
 *
 * correctOption is 1-based against the supplied option list.
 * The seed runner maps that to the Question Bank option key (A, B, C…).
 */
export const OMC_COMPUTER_BASIC_META = {
  institute: "TNS ITI AND COMPUTER INSTITUTE",
  exam: "OMC OFFICE MANAGEMENT COURSE",
  subject: "COMPUTER BASIC",
  sourceDate: "09/08/2026",
  marks: 2,
  negativeMarks: 0,
  type: "Single Choice",
  status: "Active",
  courseName: "OMC Office Management Course",
  courseCode: "TNS-OMC",
};

export const OMC_COMPUTER_BASIC_QUESTIONS = [
  {
    n: 1,
    difficulty: "Easy",
    hindi: "Excel में एक सेल से दूसरी सेल में जाने के लिए कौन सी कुंजी दबाते हैं?",
    english: "Which key is used to move from one cell to another in Excel?",
    options: ["Enter", "Space", "Tab", "Esc", "none"],
    correctOption: 3,
    correctLabel: "Tab",
    explanation:
      "The Tab key moves the active cell to the next cell horizontally in Excel.",
  },
  {
    n: 2,
    difficulty: "Medium",
    hindi: "किस कमांड की सहायता से किसी भी टेक्स्ट या ग्राफिक्स को स्थायी रूप से हटा सकते हैं।",
    options: ["डिलीट (Delete)", "क्लियर ऑल (Clear All)", "क्लियर (Clear)", "डिलीट ऑल (Delete All)", "NONE"],
    correctOption: 1,
    correctLabel: "Delete",
    explanation:
      "Delete is used to remove selected text/objects permanently from the document/application context.",
  },
  {
    n: 3,
    difficulty: "Easy",
    hindi: "किस कमांड द्वारा डॉकयुमेंट को प्रिंट करने से पहले देख सकते हैं।",
    options: ["सेंड टू", "वेब पेज प्रिव्यू", "प्रिंट प्रिव्यू", "प्रिन्ट", "NONE"],
    correctOption: 3,
    correctLabel: "Print Preview",
    explanation: "Print Preview shows the document as it will appear on paper before printing.",
  },
  {
    n: 4,
    difficulty: "Easy",
    hindi: "_______ डॉकयुमेंट को बनाने के लिए विभिन्न प्रकार के विकल्प प्रदान करते हैं।",
    options: ["माइक्रोसॉफ्ट एक्सेस", "माइक्रोसॉफ्ट एक्सेल", "माइक्रोसॉफ्ट वर्ड", "माइक्रोसॉफ्ट पावर पॉइंट", "NONE"],
    correctOption: 3,
    correctLabel: "Microsoft Word",
    explanation: "Microsoft Word is the word-processing application used to create documents.",
  },
  {
    n: 5,
    difficulty: "Easy",
    hindi: "पैराग्राफ को सेंटर अलाइन करने के लिए कौन सी कुंजी का प्रयोग किया जाता है?",
    options: ["Ctrl + Shift + D", "Ctrl + E", "Ctrl + Shift + U", "Ctrl + U", "NONE"],
    correctOption: 2,
    correctLabel: "Ctrl + E",
    explanation: "Ctrl + E centres the current paragraph in Microsoft Word.",
  },
  {
    n: 6,
    difficulty: "Easy",
    hindi: "माइक्रोसॉफ्ट एक्सेल क्या है?",
    options: [
      "एक वेब ब्राउज़र",
      "एक वर्ड प्रोसेसिंग प्रोग्राम",
      "एक ग्राफिक डिज़ाइन टूल",
      "एक स्प्रेडशीट एप्लिकेशन",
      "NONE",
    ],
    correctOption: 4,
    correctLabel: "एक स्प्रेडशीट एप्लिकेशन",
  },
  {
    n: 7,
    difficulty: "Medium",
    hindi: "एमएस एक्सेल का आविष्कार किसने और किस वर्ष किया?",
    options: [
      "रिचर्ड ब्रॉडी, 1985",
      "स्टीव जॉब्स, 1985",
      "बिल गेट्स, 1983",
      "गैरी किल्डाल, 1980",
      "NONE",
    ],
    correctOption: 5,
    correctLabel: "NONE",
    explanation:
      "The supplied options do not contain the historically accurate answer. Microsoft Excel 1.0 was released for Macintosh in 1985 by a Microsoft team (not Bill Gates in 1983). Richard Brodie is associated with Microsoft Word, Steve Jobs with Apple, and Gary Kildall with CP/M.",
  },
  {
    n: 8,
    difficulty: "Easy",
    hindi: "MS Excel में MS का क्या मतलब है?",
    options: ["मुख्य सॉफ्टवेयर", "मुख्य समाधान", "माइक्रोसॉफ्ट", "माइक्रोसॉफ्ट समाधान", "NONE"],
    correctOption: 3,
    correctLabel: "माइक्रोसॉफ्ट",
  },
  {
    n: 9,
    difficulty: "Easy",
    hindi: "वर्कशीट को हम क्या कह सकते हैं?",
    options: ["स्प्रेडशीट", "खाली पृष्ठ", "कार्य क्षेत्र", "कोई नहीं", "NONE"],
    correctOption: 1,
    correctLabel: "स्प्रेडशीट",
  },
  {
    n: 10,
    difficulty: "Easy",
    hindi: "Excel में Formula की शुरुआत किस चिन्ह से होती है?",
    english: "Which symbol starts a formula in Excel?",
    options: ["#", "$", "=", "@", "NONE"],
    correctOption: 3,
    correctLabel: "=",
    explanation: "Excel formulas always begin with an equals sign (=).",
  },
  {
    n: 11,
    difficulty: "Easy",
    hindi: "Excel में Cells को जोड़ने के लिए कौन सा चिन्ह प्रयोग होता है?",
    english: "Which symbol is used to add cells in Excel?",
    options: ["_", "*", "+", "/", "none"],
    correctOption: 3,
    correctLabel: "+",
  },
  {
    n: 12,
    difficulty: "Easy",
    hindi: "Excel में Column कैसे दिखते हैं?",
    english: "How are columns labeled in Excel?",
    options: ["Numbers", "Letters", "Symbols", "Colors", "none"],
    correctOption: 2,
    correctLabel: "Letters",
    explanation: "Excel columns are labeled A, B, C… while rows are numbered.",
  },
  {
    n: 13,
    difficulty: "Easy",
    hindi: "Excel में एक साथ कई शीट्स को क्या कहा जाता है?",
    english: "What is a group of sheets in Excel called?",
    options: ["Folder", "Workbook", "Cellbook", "Worksheet", "none"],
    correctOption: 2,
    correctLabel: "Workbook",
  },
  {
    n: 14,
    difficulty: "Easy",
    hindi: "MS Word में बनाई हुई फाइल को हम किस नाम से जानते हैं?",
    options: ["Program", "Graph", "Text", "Document", "NONE"],
    correctOption: 4,
    correctLabel: "Document",
  },
  {
    n: 15,
    difficulty: "Easy",
    hindi: "Excel में किसी डेटा को कॉपी करने के लिए शॉर्टकट क्या है?",
    english: "What is the shortcut to copy data in Excel?",
    options: ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + S", "none"],
    correctOption: 2,
    correctLabel: "Ctrl + C",
  },
  {
    n: 16,
    difficulty: "Easy",
    hindi: "एमएस पॉवरपॉइंट क्या है?",
    options: [
      "एक वीडियो एडिटिंग सॉफ्टवेयर",
      "एक स्प्रेडशीट सॉफ्टवेयर",
      "एक वर्ड प्रोसेसिंग सॉफ्टवेयर",
      "स्लाइडशो बनाने के लिए उपयोग किया जाने वाला एक प्रेजेंटेशन सॉफ्टवेयर",
      "none",
    ],
    correctOption: 4,
    correctLabel: "स्लाइडशो बनाने के लिए उपयोग किया जाने वाला एक प्रेजेंटेशन सॉफ्टवेयर",
  },
  {
    n: 17,
    difficulty: "Medium",
    hindi: "पॉवरपॉइंट का आविष्कार किसने किया?",
    options: [
      "एलन ट्यूरिंग",
      "बिल गेट्स",
      "रॉबर्ट गैस्किन्स और डेनिस ऑस्टिन",
      "स्टीव जॉब्स",
      "NONE",
    ],
    correctOption: 3,
    correctLabel: "रॉबर्ट गैस्किन्स और डेनिस ऑस्टिन",
    explanation:
      "PowerPoint was created by Robert Gaskins and Dennis Austin at Forethought; Microsoft acquired it in 1987.",
  },
  {
    n: 18,
    difficulty: "Easy",
    hindi: "PPT का पूरा नाम क्या है?",
    options: [
      "पॉवरपॉइंट प्रेजेंटेशन",
      "पब्लिक प्रेजेंटेशन टूल",
      "पर्सनल प्रेजेंटेशन टेम्प्लेट",
      "प्रोफेशनल प्रेजेंटेशन टेम्प्लेट",
      "NONE",
    ],
    correctOption: 1,
    correctLabel: "पॉवरपॉइंट प्रेजेंटेशन",
    explanation: "In common usage PPT stands for PowerPoint Presentation. Original wording/options preserved.",
  },
  {
    n: 19,
    difficulty: "Medium",
    hindi: "पॉवरपॉइंट एनिमेशन क्या हैं?",
    options: [
      "पूरी स्लाइड पर लागू होने वाले प्रभाव",
      "स्लाइड पर टेक्स्ट और ऑब्जेक्ट को गतिमान या प्रदर्शित करने वाले प्रभाव",
      "स्लाइडों के बीच ट्रांज़िशन",
      "प्रस्तुतियों में उपयोग की जाने वाली ऑडियो फ़ाइलें",
      "NONE",
    ],
    correctOption: 2,
    correctLabel: "स्लाइड पर टेक्स्ट और ऑब्जेक्ट को गतिमान या प्रदर्शित करने वाले प्रभाव",
    explanation: "Slide-to-slide effects are transitions; animations apply to objects on a slide.",
  },
  {
    n: 20,
    difficulty: "Easy",
    hindi: "अपनी स्लाइड्स में एनिमेशन जोड़ने के लिए आप किस टैब का उपयोग करेंगे?",
    options: ["डिज़ाइन", "एनिमेशन", "इन्सर्ट", "होम", "NONE"],
    correctOption: 2,
    correctLabel: "एनिमेशन",
  },
  {
    n: 21,
    difficulty: "Easy",
    hindi: "कंप्यूटर किस क्रम में संचालित होता है?",
    english: "In which sequence computer operates?",
    options: [
      "Input, output, process",
      "Input, process, output",
      "Process, input, output",
      "Output, process, input",
      "none",
    ],
    correctOption: 2,
    correctLabel: "Input, process, output",
  },
  {
    n: 22,
    difficulty: "Medium",
    hindi: "डेस्कटॉप और पर्सनल कंप्यूटर को ______ भी कहा जाता है।",
    english: "What is a desktop and personal computer also called?",
    options: ["Super Computer", "Quantum Computer", "Mainframe Computer", "Micro Computer", "none"],
    correctOption: 4,
    correctLabel: "Micro Computer",
  },
  {
    n: 23,
    difficulty: "Medium",
    hindi: "बिजली का झटका लगने पर सबसे पहले क्या कार्रवाई की जानी चाहिए?",
    english: "What is the first action to be taken in case of an electric shock?",
    options: [
      "Call to doctor",
      "Take support to others",
      "Switch OFF the electric power",
      "Call to ambulance",
      "none",
    ],
    correctOption: 3,
    correctLabel: "Switch OFF the electric power",
    explanation: "First isolate the electrical source safely before touching the affected person.",
  },
  {
    n: 24,
    difficulty: "Easy",
    hindi: "विंडोज़ ऑपरेटिंग सिस्टम में पिन किए गए एप्लिकेशन कहाँ रहते हैं?",
    english: "Where do pinned applications stay in Windows OS?",
    options: ["Desktop", "Notification Area", "Title bar", "Task Bar", "none"],
    correctOption: 4,
    correctLabel: "Task Bar",
  },
  {
    n: 25,
    difficulty: "Easy",
    hindi: "प्रिंटर द्वारा किस प्रकार की कॉपी तैयार की जाती है?",
    english: "What type of copy is produced by printer?",
    options: ["Hard Copy", "Soft Copy", "Scan Copy", "Xerox Copy", "none"],
    correctOption: 1,
    correctLabel: "Hard Copy",
  },
  {
    n: 26,
    difficulty: "Easy",
    hindi: "कंप्यूटर को चालू करने की प्रक्रिया को क्या कहते हैं?",
    options: ["स्टार्टिंग", "रनिंग", "बूटिंग", "लोडिंग", "NONE"],
    correctOption: 3,
    correctLabel: "बूटिंग",
  },
  {
    n: 27,
    difficulty: "Medium",
    hindi: "सबसे पहला कंप्यूटर का नाम क्या था?",
    options: ["ATARIS", "ENIAC", "TANDY", "NOVELLA", "none"],
    correctOption: 2,
    correctLabel: "ENIAC",
    explanation:
      "ENIAC (1945–46) is the usual textbook answer. “First computer” is historically ambiguous (Analytical Engine, Z3, Colossus, ABC, ENIAC) depending on the definition used. Original question and options preserved.",
  },
  {
    n: 28,
    difficulty: "Medium",
    hindi: "आधुनिक कम्प्यूटर की खोज सर्वप्रथम कब हुई?",
    options: ["1949", "1951", "1946", "1947", "NONE"],
    correctOption: 3,
    correctLabel: "1946",
    explanation: "ENIAC was completed and publicly demonstrated in 1946, the usual date given in fundamentals courses.",
  },
  {
    n: 29,
    difficulty: "Medium",
    hindi: "कम्प्यूटर के क्षेत्र में महान क्रांति कब से आई?",
    options: ["1977", "2000", "1955", "1960", "NONE"],
    correctOption: 5,
    correctLabel: "NONE",
    explanation:
      "The question is historically ambiguous. “Great revolution” could mean transistors/ICs (1950s–60s), the microprocessor (1971), the 1977 personal-computer trinity, or later internet eras. None of the options is a uniquely standard computer-fundamentals answer, so NONE is stored.",
  },
  {
    n: 30,
    difficulty: "Easy",
    hindi: "कंप्यूटर का हिन्दी नाम क्या है?",
    options: ["गणना करनेवाला", "संगणक", "हिसाब लगानेवाला", "परिगणक", "none"],
    correctOption: 2,
    correctLabel: "संगणक",
  },
  {
    n: 31,
    difficulty: "Easy",
    hindi: "CPU का पूर्ण रूप क्या है?",
    options: [
      "Central Processing Unit",
      "Central Processing Union",
      "Central Problem Unit",
      "इनमें से कोई नहीं",
      "none",
    ],
    correctOption: 1,
    correctLabel: "Central Processing Unit",
  },
  {
    n: 32,
    difficulty: "Medium",
    hindi: "इनमें से कौन सर्च इंजन नहीं है?",
    options: ["Google", "Yahoo", "Baidu", "Wolfram Alpha", "NONE"],
    correctOption: 4,
    correctLabel: "Wolfram Alpha",
    explanation:
      "In conventional computer-fundamentals teaching, Google, Yahoo and Baidu are search engines. Wolfram Alpha is treated as a computational knowledge engine rather than a conventional web search engine.",
  },
  {
    n: 33,
    difficulty: "Easy",
    hindi: "निम्न में कौन इनपुट इकाई है?",
    options: ["माऊस", "की-बोर्ड", "स्कैनर", "इनमें से सभी", "NONE"],
    correctOption: 4,
    correctLabel: "इनमें से सभी",
  },
  {
    n: 34,
    difficulty: "Medium",
    hindi: "एक हार्डवेयर डिवाइस जो डाटा को अर्थपूर्ण इनफार्मेशन में परिवर्तित करता है?",
    options: ["प्रोसेसर", "इनपुट डिवाइस", "प्रोग्राम", "प्रोटेक्टर", "NONE"],
    correctOption: 1,
    correctLabel: "प्रोसेसर",
  },
  {
    n: 35,
    difficulty: "Medium",
    hindi: "प्रोसेसर के तीन मुख्य भाग हैं?",
    options: [
      "ALU, कंट्रोल यूनिट और RAM",
      "ALU, कंट्रोल यूनिट और रजिस्टर",
      "कैश, कंट्रोल यूनिट और रजिस्टर",
      "इनमें से कोई नहीं",
      "NONE",
    ],
    correctOption: 2,
    correctLabel: "ALU, कंट्रोल यूनिट और रजिस्टर",
  },
  {
    n: 36,
    difficulty: "Medium",
    hindi: "CPU का मुख्य घटक है?",
    options: ["कंट्रोल यूनिट", "मेमोरी", "अर्थमैटिक लॉजिक यूनिट", "ये सभी", "none"],
    correctOption: 4,
    correctLabel: "ये सभी",
    explanation:
      "Original paper answer is “ये सभी”. Strictly, main memory (RAM) is not inside the CPU; the CPU contains the control unit, ALU and registers. Question and options preserved as supplied.",
  },
  {
    n: 37,
    difficulty: "Easy",
    hindi: "हार्ड डिस्क क्या है?",
    options: ["आउटपुट डिवाइस", "इनपुट डिवाइस", "स्टोरेज डिवाइस", "प्रोसेसर", "NONE"],
    correctOption: 3,
    correctLabel: "स्टोरेज डिवाइस",
  },
  {
    n: 38,
    difficulty: "Easy",
    hindi: "कंप्यूटर में अस्थायी मेमोरी किसे कहा जाता है?",
    options: ["ROM", "Hard Disk", "RAM", "SSD", "NONE"],
    correctOption: 3,
    correctLabel: "RAM",
  },
  {
    n: 39,
    difficulty: "Medium",
    hindi: "कंप्यूटर के आविष्कारक कौन हैं?",
    options: ["वॉन न्यूमेन", "जे एस किल्वी", "चार्ल्स बैबेज", "इनमें से कोई नहीं", "none"],
    correctOption: 3,
    correctLabel: "चार्ल्स बैबेज",
    explanation:
      "Charles Babbage is commonly known as the father of the computer because of his design of the Analytical Engine.",
  },
  {
    n: 40,
    difficulty: "Easy",
    hindi: "'Ctrl + V' का उपयोग किस लिए होता है?",
    options: ["कट करने के लिए", "कॉपी करने के लिए", "पेस्ट करने के लिए", "सेव करने के लिए", "NONE"],
    correctOption: 3,
    correctLabel: "पेस्ट करने के लिए",
  },
  {
    n: 41,
    difficulty: "Easy",
    hindi: "एमएस विंडोज़ (MS Windows) किस प्रकार का सॉफ्टवेयर है?",
    options: [
      "एप्लीकेशन सॉफ्टवेयर",
      "सिस्टम सॉफ्टवेयर / ऑपरेटिंग सिस्टम",
      "डेटाबेस सॉफ्टवेयर",
      "इनमें से कोई नहीं",
      "none",
    ],
    correctOption: 2,
    correctLabel: "सिस्टम सॉफ्टवेयर / ऑपरेटिंग सिस्टम",
  },
  {
    n: 42,
    difficulty: "Easy",
    hindi: "विंडोज़ में ग्राफिकल यूजर इंटरफेस (GUI) का क्या अर्थ है?",
    options: [
      "ग्राफिक्स यूजर इंटरनेट",
      "ग्राफिकल यूजर इंटरफेस",
      "जनरल यूजर इंटरफेस",
      "इनमें से कोई नहीं",
      "none",
    ],
    correctOption: 2,
    correctLabel: "ग्राफिकल यूजर इंटरफेस",
  },
  {
    n: 43,
    difficulty: "Easy",
    hindi: "कंप्यूटर से किसी प्रोग्राम को अनइंस्टॉल करने के लिए विंडोज़ में कहाँ जाते हैं?",
    options: ["नोटपैड", "कंट्रोल पैनल", "पेंट", "वर्डपैड", "none"],
    correctOption: 2,
    correctLabel: "कंट्रोल पैनल",
  },
  {
    n: 44,
    difficulty: "Easy",
    hindi: "विंडोज़ डेस्कटॉप पर नीचे की ओर दिखने वाली लंबी पट्टी (bar) को क्या कहते हैं?",
    options: ["मेनू बार", "टास्कबार", "स्टेटस बार", "टूल बार"],
    correctOption: 2,
    correctLabel: "टास्कबार",
    explanation: "Original source has four options only; no fifth NONE option was added.",
  },
  {
    n: 45,
    difficulty: "Easy",
    hindi: "विंडोज़ ऑपरेटिंग सिस्टम को किस कंपनी ने विकसित किया है?",
    options: ["गूगल", "माइक्रोसॉफ्ट", "एप्पल", "आईबीएम", "none"],
    correctOption: 2,
    correctLabel: "माइक्रोसॉफ्ट",
  },
  {
    n: 46,
    difficulty: "Easy",
    hindi: "निम्नलिखित में से कौन स्प्रेडशीट (Spreadsheet) से सम्बन्धित नहीं है?",
    options: [
      "वर्कशीट (Worksheet)",
      "सेल (Cell)",
      "फार्मूला (Formula)",
      "वायरस डिटेक्शन (Virus Detection)",
      "none",
    ],
    correctOption: 4,
    correctLabel: "वायरस डिटेक्शन (Virus Detection)",
  },
  {
    n: 47,
    difficulty: "Easy",
    hindi: "माइक्रोसॉफ्ट वर्ड क्या है?",
    options: [
      "माइक्रोसॉफ्ट विंडोज",
      "वर्ड प्रोसेसिंग प्रोग्राम",
      "ऑपरेटिंग सिस्टम",
      "इनमें से कोई नहीं",
      "NONE",
    ],
    correctOption: 2,
    correctLabel: "वर्ड प्रोसेसिंग प्रोग्राम",
  },
  {
    n: 48,
    difficulty: "Medium",
    hindi: "MS Word में सबसे ऊपर दिखाई देने वाली बार को क्या कहते हैं?",
    options: [
      "टास्क बार (Task Bar)",
      "टाइटल बार (Title Bar)",
      "स्टैंडर्ड टूल बार (Standard Tool Bar)",
      "टूल बार (Tool Bar)",
      "NONE",
    ],
    correctOption: 2,
    correctLabel: "टाइटल बार (Title Bar)",
  },
  {
    n: 49,
    difficulty: "Medium",
    hindi: "MS Word 2007 में फाइल को खोलने, सेव एवं बंद करने से सम्बन्धित कमांड ______ में होती हैं।",
    options: ["न्यू", "ऑफिस बटन", "होम", "इन्सर्ट", "NONE"],
    correctOption: 2,
    correctLabel: "ऑफिस बटन",
  },
  {
    n: 50,
    difficulty: "Easy",
    hindi: "Word 2010 के File menu के क्या-क्या कार्य होते हैं?",
    options: ["नई फाइल बनाना", "फाइल सेव करना", "पुरानी फाइल खोलना", "उपरोक्त सभी", "NONE"],
    correctOption: 4,
    correctLabel: "उपरोक्त सभी",
  },
];
