import { Staff } from "../modules/staff/staff.model.js";

export async function seedStaffDemo() {
  const existing = await Staff.countDocuments({ softDelete: false });
  if (existing > 0) {
    console.log(`[staff] seed skipped — ${existing} staff already exist`);
    return;
  }

  const rows = [
    {
      staffId: "TNS-STF-0001",
      personalDetails: {
        fullName: "Rekha Sharma",
        gender: "Female",
        mobile: "9479962104",
        email: "rekha.office@tns.com",
        city: "Narsinghpur",
        state: "Madhya Pradesh",
        pincode: "487001",
        address: "Ram Colony, Belapurkar Ward",
      },
      employmentDetails: {
        designation: "Office Administrator",
        department: "Administration",
        staffCategory: "Administration",
        shift: "Full Day",
        dutyStart: "09:30",
        dutyEnd: "17:30",
        weeklyOff: "Sunday",
        reportingTo: "Principal",
        qualification: "B.Com",
        experienceYears: 8,
        joiningDate: new Date("2019-06-10"),
        employmentType: "Full Time",
        monthlySalary: 18000,
      },
      emergencyContact: { name: "Ramesh Sharma", relation: "Husband", phone: "9479962199" },
      notes: "Handles admissions desk and visitor register.",
      status: "Active",
      createdBy: "seed",
      updatedBy: "seed",
    },
    {
      staffId: "TNS-STF-0002",
      personalDetails: {
        fullName: "Amit Patel",
        gender: "Male",
        mobile: "7566903104",
        email: "amit.accounts@tns.com",
        city: "Narsinghpur",
        state: "Madhya Pradesh",
        pincode: "487001",
      },
      employmentDetails: {
        designation: "Accountant",
        department: "Accounts",
        staffCategory: "Accounts & Finance",
        shift: "Morning",
        dutyStart: "09:00",
        dutyEnd: "14:00",
        reportingTo: "Office Administrator",
        qualification: "M.Com",
        experienceYears: 6,
        joiningDate: new Date("2021-04-01"),
        employmentType: "Full Time",
        monthlySalary: 22000,
      },
      emergencyContact: { name: "Suman Patel", relation: "Wife", phone: "7566903198" },
      notes: "Fee collection and daily cash book.",
      status: "Active",
      createdBy: "seed",
      updatedBy: "seed",
    },
    {
      staffId: "TNS-STF-0003",
      personalDetails: {
        fullName: "Pooja Verma",
        gender: "Female",
        mobile: "9876543210",
        email: "pooja.front@tns.com",
        city: "Narsinghpur",
        state: "Madhya Pradesh",
      },
      employmentDetails: {
        designation: "Receptionist",
        department: "Front Desk",
        staffCategory: "Administration",
        shift: "Full Day",
        dutyStart: "09:30",
        dutyEnd: "17:00",
        reportingTo: "Office Administrator",
        qualification: "DCA",
        experienceYears: 3,
        joiningDate: new Date("2023-08-15"),
        employmentType: "Full Time",
        monthlySalary: 12000,
      },
      emergencyContact: { name: "Sunita Verma", relation: "Mother", phone: "9876543299" },
      notes: "Phone enquiries and ID card issue.",
      status: "Active",
      createdBy: "seed",
      updatedBy: "seed",
    },
    {
      staffId: "TNS-STF-0004",
      personalDetails: {
        fullName: "Ravi Yadav",
        gender: "Male",
        mobile: "9826011122",
        email: "ravi.lab@tns.com",
        city: "Narsinghpur",
        state: "Madhya Pradesh",
      },
      employmentDetails: {
        designation: "IT Support Executive",
        department: "IT Support",
        staffCategory: "IT & Technical Support",
        shift: "Afternoon",
        dutyStart: "12:00",
        dutyEnd: "18:00",
        reportingTo: "HOD Computer",
        qualification: "COPA",
        experienceYears: 4,
        joiningDate: new Date("2022-01-12"),
        employmentType: "Full Time",
        monthlySalary: 14000,
      },
      emergencyContact: { name: "Mohan Yadav", relation: "Father", phone: "9826011190" },
      notes: "Computer lab 1 & 2 hardware support.",
      status: "Active",
      createdBy: "seed",
      updatedBy: "seed",
    },
    {
      staffId: "TNS-STF-0005",
      personalDetails: {
        fullName: "Suresh Kewat",
        gender: "Male",
        mobile: "9755012345",
        email: "suresh.security@tns.com",
        city: "Narsinghpur",
        state: "Madhya Pradesh",
      },
      employmentDetails: {
        designation: "Security Guard",
        department: "Security",
        staffCategory: "Security",
        shift: "Rotational",
        dutyStart: "08:00",
        dutyEnd: "16:00",
        reportingTo: "Office Administrator",
        qualification: "10th",
        experienceYears: 10,
        joiningDate: new Date("2018-03-01"),
        employmentType: "Full Time",
        monthlySalary: 11000,
      },
      emergencyContact: { name: "Kamla Kewat", relation: "Wife", phone: "9755012390" },
      notes: "Main gate and CCTV watch.",
      status: "Active",
      createdBy: "seed",
      updatedBy: "seed",
    },
  ];

  await Staff.insertMany(rows);
  console.log(`[staff] seeded ${rows.length} demo staff`);
}
